# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EventApp
  pod 'Eureka'
  pod 'JSONWebToken'
  pod 'Alamofire'
  pod 'Validator'

  target 'EventAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    
    installer.pods_project.targets.each do |target|
        
        if target.name == 'JSONWebToken'
            system("rm -rf Pods/JSONWebToken/CommonCrypto")
        end
        
    end
    
end
